#!/usr/bin/env python
import base64
import sys
import re

def concat(img_data) -> str:
    prefix = "data:image/png;base64,"
    return prefix + img_data

def main():
    file=sys.argv[1]

    with open(file, "r") as f:
        data = f.read()
        output_file = f"output_{file}"
        image_names = re.findall("!\[.*\]\((.*)\)", data)

        for image in image_names:
            with open(image, "rb") as image2string: 
                converted_string = base64.b64encode(image2string.read()) 
                data = data.replace(image, concat(converted_string.decode("utf-8")))
                
        with open(output_file, 'w') as f:
            f.write(data)
            print(f"Exported as {output_file}.")

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: Base64ImageEmbedder input.md")
        sys.exit(1)

    main()
